[placeholders.aocyear]
type = "string"
prompt = "What year does it relate to?"

[placeholders.aocday]
type = "string"
prompt = "What day does it relate to?"
choices = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
]
